.TH clmake 1 "July 2nd, 2001"
.SH NAME
clmake \- color wrapper for make(1) and less(1)
.SH SYNOPSIS
\fBclmake\fR [ --fit ] ...
.SH DESCRIPTION
clmake acts as a wrapper around make(1) to ease reading the output by
colorizing it. It also pipes the output to the \fBless\fR(1) text
pager.
.SH OPTIONS
The --fit option will truncate lines so they do not wrap. All other
options will be passed unmodified to \fBmake\fR(1).
.SH USAGE
To change a makefile to use clmake, you may change the path at the top which
normally reads \fB#!/usr/bin/make\fR to \fB#!/usr/bin/clmake\fR.
.PP
Alternately, you may type \fBclmake\fR whenever you would normally type
\fBmake\fR when compiling programs.
.SH AUTHORS
Bjarni R. Einarsson is the author of clmake.
.PP
This manual page was written for the Debian GNU/Linux distribution because
the original program does not have a manual page.
.PP
This manual page was written by Joe Wreschnig <piman@sacredchao.net>, for the
Debian GNU/Linux system (but may be used by others).
.SH SEE ALSO
\fBmake\fR\|(1), \fBcolormake\fR\|(1), \fBless\fR\|(1)
