#!/bin/bash
#
# Wrapper around make, to colorize it's output and pipe through less.
# Jumps to the first gcc error that occurs during the build process.
#

SIZE=$(stty size)
make "$@" 2>&1 | colormake.pl $SIZE | less -r -pError
exit ${PIPESTATUS[0]}
